// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxDJxvon8ACRWgDqDdcTYLOd3NRKJPEwo',
    appId: '1:289629527565:web:fa5d5f3c33513b16523f44',
    messagingSenderId: '289629527565',
    projectId: 'mobile-f-k8',
    authDomain: 'mobile-f-k8.firebaseapp.com',
    storageBucket: 'mobile-f-k8.appspot.com',
    measurementId: 'G-8DYM3895V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5z1pI1z7PumjC9FUAszaNXo02cI7hkU',
    appId: '1:289629527565:android:46cc5b2ea9879a66523f44',
    messagingSenderId: '289629527565',
    projectId: 'mobile-f-k8',
    storageBucket: 'mobile-f-k8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhsFLyshsscuJswKNcT_h4Yyf98TDiNRw',
    appId: '1:289629527565:ios:6fdf37d608bb748f523f44',
    messagingSenderId: '289629527565',
    projectId: 'mobile-f-k8',
    storageBucket: 'mobile-f-k8.appspot.com',
    iosClientId: '289629527565-rfar90do7d98r603s0pggsnins85bu05.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhsFLyshsscuJswKNcT_h4Yyf98TDiNRw',
    appId: '1:289629527565:ios:070681400395451e523f44',
    messagingSenderId: '289629527565',
    projectId: 'mobile-f-k8',
    storageBucket: 'mobile-f-k8.appspot.com',
    iosClientId: '289629527565-e2n7b0vv0cseq1hudnfm8ea8v6376h3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileProject.RunnerTests',
  );
}
